services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./uploads:/app/uploads
    networks:
    - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U teensregister -d teensconf"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./teens_rega_back
      dockerfile: Dockerfile
    ports:
        - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    env_file:
      - .env  
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
    volumes:
      - ./uploads:/app/uploads:rw
    networks:
      - app-network

  frontend:
    build:
      context: ./teens_rega_front
      dockerfile: Dockerfile
    ports:
        - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
    networks:
      - app-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8090:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181 
    networks:
      - app-network 

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: redis-server --appendonly yes

  
  yandex_microservice:
    build:
      context: ./yandex_microservice
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
    env_file:
      - yandex_microservice/.env
    depends_on:
      redis:
        condition: service_healthy
      kafka:
        condition: service_started
      backend:
        condition: service_started
    ports:
      - "8081:8080"
    volumes:
      - ./uploads:/app/uploads
    networks:
      - app-network

#  nginx:
#    image: nginx:alpine
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - ./nginx.conf:/etc/nginx/nginx.conf
#      - /etc/letsencrypt:/etc/letsencrypt:ro
#    depends_on:
#      - frontend
#      - backend
#    networks:
#      - app-network

volumes:
  postgres_data:
#  uploads_data:

networks:
 app-network:
   driver: bridge