CREATE TABLE payment_receipts
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    registration_id    BIGINT                                  NOT NULL,
    donation_amount    DOUBLE PRECISION,
    paid               BOOLEAN,
    payment_reference  VARCHAR(255),
    file_name          VARCHAR(255),
    file_path          VARCHAR(255),
    file_size          BIGINT,
    verified           BOOLEAN,
    payment_created_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_payment_receipts PRIMARY KEY (id)
);

CREATE TABLE registrations
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name                VARCHAR(255)                            NOT NULL,
    last_name                 VARCHAR(255)                            NOT NULL,
    email                     VARCHAR(255)                            NOT NULL,
    birth_date                VARCHAR(255)                            NOT NULL,
    phone                     VARCHAR(255)                            NOT NULL,
    telegram                  VARCHAR(255)                            NOT NULL,
    city                      VARCHAR(255)                            NOT NULL,
    need_accommodation        BOOLEAN,
    church                    VARCHAR(255)                            NOT NULL,
    role                      VARCHAR(255)                            NOT NULL,
    parent_full_name          VARCHAR(255),
    parent_phone              VARCHAR(255),
    consent_under_14          BOOLEAN,
    consent_donation          BOOLEAN,
    consent_personal_data     BOOLEAN,
    was_before                BOOLEAN,
    registration_created_at   TIMESTAMP WITHOUT TIME ZONE,
    registration_completed_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_registrations PRIMARY KEY (id)
);

ALTER TABLE payment_receipts
    ADD CONSTRAINT uc_payment_receipts_registration UNIQUE (registration_id);

ALTER TABLE payment_receipts
    ADD CONSTRAINT FK_PAYMENT_RECEIPTS_ON_REGISTRATION FOREIGN KEY (registration_id) REFERENCES registrations (id);